package com.bcs.core.enums;

public enum RECORD_REPORT_TYPE {

	REFERENCE_ID_USER_GROUP("USER_GROUP"),
	REFERENCE_ID_COUNT_RECEIVE("COUNT_RECEIVE"),
	
	CONTENT_TYPE_INTERACTIVE("INTERACTIVE"),
	DATA_TYPE_INTERACTIVE_UNBIND_COUNT("UNBIND_COUNT"),
	DATA_TYPE_INTERACTIVE_UNBIND_DISTINCT_COUNT("UNBIND_DISTINCT_COUNT"),
	DATA_TYPE_INTERACTIVE_BINDED_COUNT("BINDED_COUNT"),
	DATA_TYPE_INTERACTIVE_BINDED_DISTINCT_COUNT("BINDED_DISTINCT_COUNT"),

	CONTENT_TYPE_RECEIVE_OP("RECEIVE_OP"),
	DATA_TYPE_RECEIVE_OP_ADD_COUNT("ADD_COUNT"),
	DATA_TYPE_RECEIVE_OP_BLOCK_COUNT("BLOCK_COUNT"),
	
	CONTENT_TYPE_USER_GROUP("USER_GROUP"),
	DATA_TYPE_USER_GROUP_BINDED_COUNT("BINDED_COUNT"),
	DATA_TYPE_USER_GROUP_UNBIND_COUNT("UNBIND_COUNT"),
	DATA_TYPE_USER_GROUP_BINDED_TO_BLOCK_COUNT("BINDED2BLOCK_COUNT"),

	CONTENT_TYPE_LINK_URL("LINK_URL"),
	DATA_TYPE_LINK_COUNT("LINK_COUNT"),
	DATA_TYPE_LINK_DISTINCT_COUNT("LINK_DISTINCT_COUNT"),

	CONTENT_TYPE_LINK_ID("LINK_ID"),

	CONTENT_TYPE_PAGE_URL("PAGE_URL"),
	DATA_TYPE_PAGE_COUNT("PAGE_COUNT"),
	DATA_TYPE_PAGE_DISTINCT_COUNT("PAGE_DISTINCT_COUNT"),

	CONTENT_TYPE_COUPON_GET("COUPON_GET"),
	CONTENT_TYPE_COUPON_USE("COUPON_USE"),
	DATA_TYPE_COUPON_COUNT("COUPON_COUNT"),
	DATA_TYPE_COUPON_DISTINCT_COUNT("COUPON_DISTINCT_COUNT"),
	;

    private final String str;
    
    RECORD_REPORT_TYPE(String str) {
        this.str = str;
    }
	/**
	 * @return the str
	 */
	public String toString() {
		return str;
	}
}
